spring.application.name=his-backend
spring.profiles.active=prod
server.port=8080

# Configuraci?n de la base de datos PostgreSQL (Local)
spring.datasource.url=jdbc:postgresql://localhost:5432/his
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuraci?n de HikariCP (pool de conexiones)
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-His

# Configuraci?n de JPA/Hibernate
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicializaci?n de SQL (opcional)
spring.sql.init.platform=postgres

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui-custom.html
# Deshabilitar endpoints de documentación en producción
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
spring.web.resources.static-locations=classpath:/static/

# Logging
logging.level.org.springframework=INFO

# JWT Configuration
jwt.secret.key=cHL5E41qNTtMSLXr3djdEI5JFCg9DpTovQCOhhPNV/pyo9Y357RXidj08B3Z3Q3KZZzwyzzz21YmZ4a7Z9LcSzOg51pt/bFssEc2dUU0lqkoq1zVb4W83+1TTbjwzREvEUdmL2hD9tWEOpomvTvY4vH1N9bXzWtGOILeZAxYo6zXZ8V8LnmP36GFZsXFUpveHTk+5+3CDctQGlZNA2NnEyK7XEom97aVuOlSBBH3Js2XOaL74zDr3COs0X95oNQqJCd0dbBA1u1Y0/meXHd7DCmCjm6TtIAdUuetF8nttVxg6VTCmwWxeoqY6Ha2N6+ZxFymy9w8xu+94kueXD8YVIY8Pt6NtRniKTSV4BB1F9s=
jwt.expiration.hours=24
